spring:
  application:
    name: sit727-chat-app
  datasource:
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/chatdb
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080