spring:
  application:
    name: sit727-chat-app
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080