apiVersion: v1
kind: Service
metadata:
  name: mysql-replica-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-replica
  clusterIP: None  # Headless service for StatefulSet
