# mysql-replica-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-replica-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-replica"
